export type SelectOption = string | { value: string; label: string };

export type MA2Direction = 'press' | 'release';
export type MA2DownUpDirection = 'true' | 'false';
export type MA2RotateDirection = '-1' | '1';

export const MA2_DIRECTION_OPTIONS: SelectOption[] = [
  { value: 'press', label: 'Press' },
  { value: 'release', label: 'Release' },
];
export const MA2_DOWN_UP_OPTIONS: SelectOption[] = [
  { value: 'true', label: 'Press (down)' },
  { value: 'false', label: 'Release (up)' },
];
export const MA2_ROTATE_DIRECTION_OPTIONS: SelectOption[] = [
  { value: '-1', label: 'CCW' },
  { value: '1', label: 'CW' },
];
export const MA2_ENCODER_SELECT_OPTIONS: SelectOption[] = [
  { value: '0', label: 'Main Encoder (1)' },
  { value: '1', label: 'Main Encoder (2)' },
  { value: '2', label: 'Main Encoder (3)' },
  { value: '3', label: 'Main Encoder (4)' },
  { value: '4', label: 'Command Screen Encoder (5)' },
  { value: '5', label: 'Screen 2 Encoder (6)' },
  { value: '6', label: 'Screen 3 Encoder (7)' },
  { value: '7', label: 'Screen 4 Encoder (8)' },
];
export const MA2_BUTTON_OPTIONS: SelectOption[] = [
  { value: '3', label: 'Ch Pg +' },
  { value: '4', label: 'Ch Pg -' },
  { value: '5', label: 'Fd Pg +' },
  { value: '6', label: 'Fd Pg -' },
  { value: '7', label: 'Bt Pg +' },
  { value: '8', label: 'Bt Pg -' },
  { value: '9', label: 'Pause Playback' },
  { value: '10', label: 'Go - Playback' },
  { value: '11', label: 'Go + Playback' },
  { value: '12', label: 'X1' },
  { value: '13', label: 'X2' },
  { value: '14', label: 'X3' },
  { value: '15', label: 'X4' },
  { value: '16', label: 'X5' },
  { value: '17', label: 'X6' },
  { value: '18', label: 'X7' },
  { value: '19', label: 'X8' },
  { value: '20', label: 'X9' },
  { value: '21', label: 'X10' },
  { value: '22', label: 'X11' },
  { value: '23', label: 'X12' },
  { value: '24', label: 'X13' },
  { value: '25', label: 'X14' },
  { value: '26', label: 'X15' },
  { value: '27', label: 'X16' },
  { value: '28', label: 'X17' },
  { value: '29', label: 'X18' },
  { value: '30', label: 'X19' },
  { value: '31', label: 'X20' },
  { value: '32', label: 'List' },
  { value: '33', label: 'User 1' },
  { value: '34', label: 'User 2' },
  { value: '36', label: 'U1' },
  { value: '37', label: 'U2' },
  { value: '38', label: 'U3' },
  { value: '39', label: 'U4' },
  { value: '40', label: 'Nipple' },
  { value: '41', label: 'Fix' },
  { value: '42', label: 'Select' },
  { value: '43', label: 'Off' },
  { value: '44', label: 'Temp' },
  { value: '45', label: 'Top' },
  { value: '46', label: 'On' },
  { value: '47', label: '<<<' },
  { value: '48', label: 'Learn' },
  { value: '49', label: '>>>' },
  { value: '50', label: 'Go -' },
  { value: '51', label: 'Pause' },
  { value: '52', label: 'Go +' },
  { value: '53', label: 'Oops' },
  { value: '54', label: 'Esc' },
  { value: '55', label: 'Edit' },
  { value: '56', label: 'Goto' },
  { value: '57', label: 'Update' },
  { value: '58', label: 'Time' },
  { value: '59', label: 'Store' },
  { value: '60', label: 'Blind' },
  { value: '61', label: 'Freeze' },
  { value: '62', label: 'Preview' },
  { value: '63', label: 'Assign' },
  { value: '64', label: 'Align' },
  { value: '65', label: 'Blackout' },
  { value: '66', label: 'View' },
  { value: '67', label: 'Effect' },
  { value: '68', label: 'MA' },
  { value: '69', label: 'Delete' },
  { value: '70', label: 'Page' },
  { value: '71', label: 'Macro' },
  { value: '72', label: 'Preset' },
  { value: '73', label: 'Copy' },
  { value: '74', label: 'Sequence' },
  { value: '75', label: 'Cue' },
  { value: '76', label: 'Executor' },
  { value: '82', label: 'Channel' },
  { value: '83', label: 'Fixture' },
  { value: '84', label: 'Group' },
  { value: '85', label: 'Move' },
  { value: '86', label: '0' },
  { value: '87', label: '1' },
  { value: '88', label: '2' },
  { value: '89', label: '3' },
  { value: '90', label: '4' },
  { value: '91', label: '5' },
  { value: '92', label: '6' },
  { value: '93', label: '7' },
  { value: '94', label: '8' },
  { value: '95', label: '9' },
  { value: '96', label: '+' },
  { value: '97', label: '-' },
  { value: '98', label: '.' },
  { value: '99', label: 'Full' },
  { value: '100', label: 'Highlight' },
  { value: '101', label: 'Solo' },
  { value: '102', label: 'Thru' },
  { value: '103', label: 'If' },
  { value: '104', label: 'At' },
  { value: '105', label: 'Clear' },
  { value: '106', label: 'Please' },
  { value: '107', label: 'Up' },
  { value: '108', label: 'Set' },
  { value: '109', label: 'Previous' },
  { value: '110', label: 'Next' },
  { value: '111', label: 'Down' },
  { value: '116', label: 'Help' },
  { value: '117', label: 'Backup' },
  { value: '118', label: 'Setup' },
  { value: '119', label: 'Tools' },
  { value: '120', label: 'V1' },
  { value: '121', label: 'V2' },
  { value: '122', label: 'V3' },
  { value: '123', label: 'V4' },
  { value: '124', label: 'V5' },
  { value: '125', label: 'V6' },
  { value: '126', label: 'V7' },
  { value: '127', label: 'V8' },
  { value: '128', label: 'V9' },
  { value: '129', label: 'V10' },
];
export const MA2_FUNCTIONS = new Set<string>([
  'Button Press/Release',
  'Encoder Press/Release',
  'Move wheel up/down',
  'Rotate Encoder',
  'Run Custom Command',
]);
export const GENERIC_TCP_UDP_FUNCTIONS = new Set<string>([
  'Send Command',
  'Send HEX encoded Command',
]);
export const COMPANION_REMOTE_FUNCTIONS = new Set<string>(['Button Event']);
export const COMPANION_SATELLITE_EVENT_OPTIONS: SelectOption[] = [
  { value: 'press', label: 'Press' },
  { value: 'release', label: 'Release' },
  { value: 'rotate_left', label: 'Rotate Left' },
  { value: 'rotate_right', label: 'Rotate Right' },
];
export const SWP08_FUNCTIONS = new Set<string>([
  'Select Levels',
  'De-Select Levels',
  'Toggle Levels',
  'Select Destination',
  'Select Destination name',
  'Select Source',
  'Select Source name',
  'Route Source to selected Levels and Destination',
  'Route Source name to selected Levels and Destination',
  'Take',
  'Clear',
  'Set crosspoint',
  'Set crosspoint by name',
  'Refresh Source and Destination names',
]);
export const VIDEOHUB_FUNCTIONS = new Set<string>([
  'Lock: Change destination lock state',
  'Lock: Change destination lock state (dynamic)',
  'Route File: Load file',
  'Route File: Save file',
  'Video: Clear queued route',
  'Video: Rename destination',
  'Video: Rename source',
  'Video: Return to previous route',
  'Video: Return to previous route (dynamic)',
  'Video: Route source to destination',
  'Video: Route source to destination (dynamic)',
  'Video: Route source to destination, based on another destination',
  'Video: Route source to destination, based on another destination (dynamic)',
  'Video: Route source to selected destination',
  'Video: Route source to selected destination (dynamic)',
  'Video: Select destination',
  'Video: Select destination (dynamic)',
  'Video: Take queued route',
]);
export const VIDEOHUB_LOCK_STATE_OPTIONS: SelectOption[] = [
  { value: 'T', label: 'Toggle' },
  { value: 'L', label: 'Lock' },
  { value: 'U', label: 'Unlock' },
];
export const VIDEOHUB_LOCK_STATE_DYNAMIC_OPTIONS: SelectOption[] = [
  { value: 'toggle', label: 'Toggle' },
  { value: 'lock', label: 'Lock' },
  { value: 'unlock', label: 'Unlock' },
];
export const SWP08_CLEAR_OPTIONS: SelectOption[] = [
  { value: 'all', label: 'All' },
  { value: 'level', label: 'Levels' },
  { value: 'dest', label: 'Destination' },
  { value: 'source', label: 'Source' },
];
export const GENERIC_HTTP_FUNCTIONS = new Set<string>([
  'GET',
  'POST',
  'PUT',
  'PATCH',
  'DELETE',
]);
export const GENERIC_HTTP_CONTENT_TYPE_OPTIONS: SelectOption[] = [
  { value: 'application/json', label: 'application/json' },
  {
    value: 'application/x-www-form-urlencoded',
    label: 'application/x-www-form-urlencoded',
  },
  { value: 'application/xml', label: 'application/xml' },
  { value: 'text/html', label: 'text/html' },
  { value: 'text/plain', label: 'text/plain' },
  { value: 'text/csv', label: 'text/csv' },
  { value: 'text/xml', label: 'text/xml' },
  { value: 'multipart/form-data', label: 'multipart/form-data' },
  { value: 'application/octet-stream', label: 'application/octet-stream' },
  { value: 'application/javascript', label: 'application/javascript' },
  { value: 'application/pdf', label: 'application/pdf' },
  { value: 'application/zip', label: 'application/zip' },
  { value: 'image/png', label: 'image/png' },
  { value: 'image/jpeg', label: 'image/jpeg' },
  { value: 'image/svg+xml', label: 'image/svg+xml' },
  { value: 'application/ld+json', label: 'application/ld+json' },
  { value: 'application/vnd.api+json', label: 'application/vnd.api+json' },
  { value: 'application/x-yaml', label: 'application/x-yaml' },
  { value: 'application/graphql', label: 'application/graphql' },
];
export const GENERIC_OSC_FUNCTIONS = new Set<string>([
  'Send blob',
  'Send boolean',
  'Send float',
  'Send int',
  'Send multiple',
  'Send blank',
  'Send midi',
  'Send string',
]);
export const GENERIC_OSC_MIDI_MODE_OPTIONS: SelectOption[] = [
  { value: 'noteon', label: 'noteon' },
  { value: 'noteoff', label: 'noteoff' },
  { value: 'cc', label: 'cc' },
  { value: 'pitchbend', label: 'pitchbend' },
  { value: 'raw', label: 'raw' },
];
export const GENERIC_TCP_UDP_LINE_END_OPTIONS: SelectOption[] = [
  { value: '\n', label: 'LF - \\n (Common UNIX/Mac)' },
  { value: '\r\n', label: 'CRLF - \\r\\n (Common Windows)' },
  { value: '\r', label: "CR - \\r (1970's RS232 terminal)" },
  { value: '\x00', label: 'NULL - \\x00 (Can happen)' },
  { value: '\n\r', label: 'LFCR - \\n\\r (Just weird)' },
];
